export const ROUTES = {
  LOGIN: "/dang-nhap",
  FORGOT_PASSWORD: "/quen-mat-khau",
  VISITOR: "/khach-tham-quan",
  MAJORS: "/nganh-hoc",
  GUIDE: "/huong-dan",
  CONTACT: "/lien-he",
  VISITOR_DETAIL: "/chi-tiet-san-pham",
  PROFILE: "/ho-so",
  ADMIN: "/quan-tri",
  STUDENT: "/sinh-vien",
  TEACHER: "/giang-vien",
  UPLOAD_PRODUCT: "/dang-san-pham",
  EDIT_PRODUCT: "/chinh-sua-san-pham",
  STUDENT_DETAIL: "/chi-tiet-cua-toi",
  TEACHER_DETAIL: "/giang-vien/chi-tiet-san-pham",
  COMPARE_AI: "/so-sanh-ai",
};

export const LEGACY_ROUTES = [
  ["/login", ROUTES.LOGIN],
  ["/forgot", ROUTES.FORGOT_PASSWORD],
  ["/nckh-visitor", ROUTES.VISITOR],
  ["/visitor-detail", ROUTES.VISITOR_DETAIL],
  ["/visitor-detail/:id", `${ROUTES.VISITOR_DETAIL}/:id`],
  ["/nckh-profile", ROUTES.PROFILE],
  ["/nckh-admin", ROUTES.ADMIN],
  ["/nckh-student", ROUTES.STUDENT],
  ["/nckh-teacher", ROUTES.TEACHER],
  ["/upload", ROUTES.UPLOAD_PRODUCT],
  ["/edit-product", ROUTES.EDIT_PRODUCT],
  ["/detail", ROUTES.STUDENT_DETAIL],
  ["/detail-teacher", ROUTES.TEACHER_DETAIL],
  ["/nckh-compare", ROUTES.COMPARE_AI],
];
